# Generated by Django 3.0.6 on 2020-05-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200516_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
    ]
