# Generated by Django 3.0.6 on 2020-05-16 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200516_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votes_up',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
