# Generated by Django 3.0.6 on 2020-05-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200516_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes_num',
            new_name='votes_count',
        ),
    ]
