# Generated by Django 3.0.6 on 2020-05-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_count',
        ),
    ]
