# Generated by Django 3.0.6 on 2020-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_votes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='content',
            field=models.CharField(max_length=4),
        ),
    ]
