# Generated by Django 3.0.6 on 2020-05-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
